# # Manifest for green deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-green
  namespace: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
      version: green
  template:
    metadata:
      labels:
        app: nodejs
        version: green
    spec:
      containers:
      - name: nodejs
        image: ankitofficial1821/hello-node-app:1.0.0
        ports:
        - containerPort: 3000