apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-job
  namespace: kaniko
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - --dockerfile=Dockerfile
        - --context=git://github.com/Ankitdevops18/nodejs-sample.git#refs/heads/master
        - --destination=docker.io/ankitofficial1821/hello-node-app:latest
        - --verbosity=debug
        - --insecure
        - --skip-tls-verify
        - --cache=false
        env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
        volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
      volumes:
      - name: docker-config
        secret:
          secretName: regcred