apiVersion: v1
kind: Service
metadata:
  name: nodejs-blue-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nodejs-blue  # or nodejs-blue based on which you want to serve
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000